### ISSUE TITLE
Inquiry and Assistance Required for Code Execution and Data Usage

### ISSUE THREAD

**Issue by majixin-li** [cut-dicl/cibap#1]
Dear friend,

I hope this message finds you well. Firstly, I would like to express my appreciation for the effort you put into creating the code. However, I encountered some difficulties while attempting to run it. I have a few questions and concerns that I would like to address:

I'm unsure about the purpose of the data contained in the "data" folder within the "Data_and_Results" directory. Could you please clarify what this data represents and provide instructions on how to utilize it?

I apologize for any inconvenience caused, and I greatly appreciate your time and assistance in addressing these queries. Thank you very much for your attention to this matter.

Best regards,
Ma Jx

**Comment by cut-dicl** [comment]
Dear Ma,

We appreciate your interest in our project.

The "data" folder contain the randomly generated data instances used in our paper: https://www.mdpi.com/2077-1312/11/7/1280/htm

We can explain the file name convention using a simple example:
"10v1d1q" --> It shows this data instance considering 10 vessels, 1 day (24 hours) planning horizon, and 1 quay.

A similar notation is used for the results folders containing the results of the different algorithms. For example, in CSA, first result is: 
"BP_CSA_10v1d1q" -> BP (berthing position) results of CSA considering 10 vessels, 1 day, and 1 quay. 
BT -> berthing time
BQ -> berthing quay

Please read our paper to check abbreviations used in results and data instances.
paper link: https://www.mdpi.com/2077-1312/11/7/1280/htm

Thank you.

**Comment by cut-dicl** [comment]
Dear Ma, please find our response online: https://github.com/cut-dicl/cibap/issues/1

--
Herodotos Herodotou
Assistant Professor
Director of the Data Intensive Computing Research Lab (DICL<https://dicl.cut.ac.cy/>)
Dept. of Electrical Eng., Computer Eng. and Informatics (EECEI<https://www.cut.ac.cy/faculties/fet/eecei/>)
Cyprus University of Technology (CUT<https://www.cut.ac.cy/>)

From: majixin-li ***@***.***>
Sent: Tuesday, June 20, 2023 5:31 PM
To: cut-dicl/cibap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cut-dicl/cibap] Inquiry and Assistance Required for Code Execution and Data Usage (Issue #1)


Dear friend,

I hope this message finds you well. Firstly, I would like to express my appreciation for the effort you put into creating the code. However, I encountered some difficulties while attempting to run it. I have a few questions and concerns that I would like to address:

1、I couldn't locate any program starting with "Main_" within the "milp" folder in the "MATLAB_CODE" directory. Could you kindly provide guidance on how to run the code properly?

2、I'm unsure about the purpose of the data contained in the "data" folder within the "Data_and_Results" directory. Could you please clarify what this data represents and provide instructions on how to utilize it?

I apologize for any inconvenience caused, and I greatly appreciate your time and assistance in addressing these queries. Thank you very much for your attention to this matter.

Best regards,
Ma Jx
